before_script:
  - export PATH="$PATH:/home/vivoadmin/.cargo/bin"
  - rustup toolchain link mygnutoolchain "/home/vivoadmin/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu"
  - rustup default mygnutoolchain

build-job:
  stage: build
  script:
    - mdbook build
