[book]
title = "The vivo BlueOS kernel"
author = "vivo BlueOS project Developers"
description = "A development guide of the vivo BlueOS kernel"

[build]
create-missing = false

[output.html.playground]
editable = false
copyable = true
copy-js = true
line-numbers = true
runnable = false

[preprocessor.gettext]
after = ["links"]